name: Mirror Dockerhub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: alpine
            repo: docker.io
          - image: docker
            repo: docker.io
          - image: nextcloud
            repo: docker.io
          - image: mariadb
            repo: docker.io
          - image: postgres
            repo: docker.io
          - image: redis
            repo: docker.io
          - image: traefik
            repo: docker.io
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: actions/setup-go@v4
      - uses: imjasonh/setup-crane@v0.3
      - name: Mirror
        run: |
          for tag in $(cat ./images/${{ matrix.image }}); do
            crane copy \
              ${{ matrix.repo }}/${{ matrix.image }}:$tag \
              ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:$tag;
            sleep 60;
          done

  clean-ghcr:
    name: Delete old container images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: alpine
          - image: docker
          - image: nextcloud
          - image: mariadb
          - image: postgres
          - image: redis
          - image: traefik
    steps:
      - name: Delete untagged images
        uses: snok/container-retention-policy@v2
        with:
          image-names: ${{ matrix.image }}
          cut-off: One hour ago UTC
          account-type: personal
          token: ${{ secrets.TOKEN_DELETE_GHCR_IMAGES }}
          keep-at-least: 0
          untagged-only: True
          skip-tags: latest
          dry-run: False
