name: Mirror Dockerhub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: alpine
            repo: docker.io
            platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          - image: mariadb
            repo: docker.io
            platforms: linux/amd64,linux/arm64/v8
          - image: postgres
            repo: docker.io
            platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          - image: docker
            repo: docker.io
            platforms: linux/amd64,linux/arm64/v8

    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Mirror
        run: |
          for tag in $(cat ./images/${{ matrix.image }}); do
            docker buildx build \
              --platform ${{ matrix.platforms }} \
              --build-arg REPO=${{ matrix.repo }} \
              --build-arg IMAGE=${{ matrix.image }} \
              --build-arg TAG=$tag \
              --label org.opencontainers.image.source=https://github.com/${{ github.repository }} \
              --tag ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:$tag \
              --push \
              .
          done
